### PR TITLE
Add an option to set page background color

### PR DESCRIPTION
**Pull request by henriquecfreitas**

### CODE REVIEW

**Comment by quaardvark** [comment]
@henriquecfreitas @pkrawc I'm wondering if setting the background on wrapper is good enough, - I would prefer it on the body to be honest

**Comment by pkrawc** [comment]
I would also prefer it on the body.

@henriquecfreitas one can create a global style tag anywhere in the app with `createGlobalStyle`

I would suggest the following.

```jsx
const BodyStyles = createGlobalStyle(
  ({ bg }) => css`
    body {
      background: ${bg};
    }
  `
)

function InfoPage() {
  return (
    <Fragment>
      <BodyStyles bg={background} />
      <Box /> // Page Stuff
    </Fragment>
  )
}
```

You cool with that @quaardvark ?

**Comment by pkrawc** [comment]
Almost 100% that the global style tag will be removed from the DOM when the component is unmounted. But that's something we should probably check for.

**Comment by pkrawc** [comment]
You'll also probably want to add a default option to that prop (eg. `bg = "#f3f3f3"`)

**Review by quaardvark — APPROVED** [review]

**Pull request merged**
