### PR TITLE
Create Standard NavBar Organism

### PR DESCRIPTION
**Pull request by nshonda**
- Adding new Prismic types (Navbar and NavbarMenu)
- Using Avail/RDC navbar across all pages
- adding support to 1st level navigation
- adding tag support to child links
- copying existing menu to static navbar

### CODE REVIEW

**Comment by nshonda** [comment]
@quaardvark leaving this as a draft PR for now

**Comment by quaardvark** [comment]
@nshonda can you check why the build is failing? You can try locally with `yarn build`. It seems to be happening in `[uid].page.js` - I don't think this PR should contain any changes for this page

**Review by quaardvark — COMMENTED** [review]
I'm not sure if I fully understand the flow of work here, but I though we were going to add a new NavBar organism instead of modifying existing NavBars that are already used on paid search pages.

**Comment by nshonda** [comment]
@quaardvark ah I see, okay, there's no problem I can convert my changes into a new organism then and revert the existing NavBars to the state they were on pages/main branch

**Review by quaardvark — APPROVED** [review]

**Pull request merged**
