### PR TITLE
Created the offset on Hero images

### PR DESCRIPTION
**Pull request by taylorsavegnago**
New prop on Hero images:

offset: {
  top: "0",
  right: "0",
  left: "0",
  bottom: "0"
},

It means where you want the image to be located in the Hero

image

image

### CODE REVIEW

**Review by quaardvark — CHANGES_REQUESTED** [review]
I don't think it should be defined as offset, because it would be hard to use when implemented in Prismic. I think the Prismic data should be just `imagePosition: "offset-bottom"` and just make it stick to the bottom.

**Review by quaardvark — CHANGES_REQUESTED** [review]
There's something weird is happening on different screen sizes

Screenshot_20210830_151159

**Comment by taylorsavegnago** [comment]
> There's something weird is happening on different screen sizes
> 
> Screenshot_20210830_151159

I fixed the height of Hero according to the old page (https://www.avail.co/landlords/features). Used 56rem.

**Review by quaardvark — CHANGES_REQUESTED** [review]
Please, do not change the hero height

**Comment by quaardvark** [comment]
@nshonda @taylorsavegnago FYI this was implemented properly now, but it looks strange on big screens, so I asked Vinnie to review it

**Pull request merged**
